- become: yes
  hosts: all
  name: ovpn-install
  tasks:

    - name: Update all packages
      apt:
        update_cache: yes

    - name: Download OpenVPN installation script
      get_url:
        url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
        dest: /opt/openvpn-install.sh
        mode: 0700

    - name: Install and setup OpenVPN
      shell: /opt/openvpn-install.sh
      environment:
        AUTO_INSTALL: y
        CLIENT: "{{ lookup('env', 'SERVER_NAME') }}"
    
    - name: Download ovpn config
      fetch:
        src: ~/client.ovpn
        dest: "~/vpn"

  handlers:
    - name: Restart OpenVPN
      service: name=openvpn@server state=restarted
